name: lint helm charts
run-name: lint helm charts by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request: 
    types:
      - closed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up helm ðŸ”§
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: setup python ðŸ”§
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: set up chart-testing ðŸ”§
        uses: helm/chart-testing-action@v2.4.0

      - name: run chart-testing (list-changed) ðŸ“¦
        id: list-changed
        run: |
          changed=$(ct list-changed --config config/helm-configuration.yaml --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
              echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: run chart-testing (lint) ðŸ“¦
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config config/helm-configuration.yaml --target-branch ${{ github.event.repository.default_branch }}
